curl "http://localhost:3002/api/periods/5f6ccc5979667704d333c5d7" ^
  -H "Connection: keep-alive" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36" ^
  -H "Sec-Fetch-Site: same-origin" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Referer: http://localhost:3002/appraisals/5f6ccc5979667704d333c5d7/users/nonmember/items" ^
  -H "Accept-Language: en-US,en;q=0.9" ^
  -H "Cookie: connect.sid=s%3APSpRRC1-m78o-Qg5QL0KhpWXv-n45Kh7.nlEFd%2BtS2tc0PYrpFUnvSDi7RhmP3Mblj940TusqgQw
  -H "If-None-Match: W/^\^"3c0-/qED2PCxSr5oLSVgJMMhVyZEHLw^\^"" ^
  --compressed